const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const GrilleLogic = require('../js/grille-cipher-logic.js');
const GrilleSamples = require('../js/samples.js');

const root = path.join(__dirname, '..');
const readme = fs.readFileSync(path.join(root, 'README.md'), 'utf8');

function section(title, nextTitle) {
  const start = readme.indexOf(title);
  assert.notEqual(start, -1, `missing ${title}`);
  const end = nextTitle ? readme.indexOf(nextTitle, start + title.length) : readme.length;
  assert.notEqual(end, -1, `missing ${nextTitle}`);
  return readme.slice(start, end);
}

function rows(markdown) {
  return markdown.split(/\r?\n/)
    .filter(line => /^\|/.test(line) && !/^\|\s*-/.test(line))
    .slice(1)
    .map(line => line.slice(1, -1).split('|').map(cell => cell.trim()));
}

test('key table is generated by the declared keys', () => {
  const table = rows(section('## 🔑 鍵の表し方', '## 🧩 例で確かめる'));
  assert.equal(table.length, 2);
  const expected = [GrilleLogic.DEFAULT_KEY, GrilleSamples.find(sample => sample.id === 'sandorf').key];
  table.forEach((row, index) => {
    assert.equal(row[1], expected[index]);
    assert.equal(row[2].replaceAll('⏎', '\n'), GrilleLogic.formatHolePattern(expected[index]));
  });
});

test('encryption examples match the cipher implementation', () => {
  const part = section('## 🧩 例で確かめる', '## ⌨️ キーボードショートカット');
  const table = rows(part).slice(0, 4);
  assert.equal(table.length, 4);
  const sandorf = GrilleSamples.find(sample => sample.id === 'sandorf');
  const examples = [
    { plain: 'HAPPY HOLIDAYS FROM THE HUNTINGTON FAMILY', key: '241143322', direction: 'cw' },
    { plain: 'HAPPY HOLIDAYS FROM THE HUNTINGTON FAMILY', key: '241143322', direction: 'ccw' },
    { plain: 'ATTACK AT DAWN', key: '241143322', direction: 'cw' },
    { plain: sandorf.plain, key: sandorf.key, direction: 'cw' }
  ];
  table.forEach((row, index) => {
    const encrypted = GrilleLogic.encrypt(examples[index].plain, examples[index].key, {
      direction: examples[index].direction,
      filler: count => 'X'.repeat(count)
    });
    assert.equal(row[1], examples[index].key);
    assert.equal(row[2], examples[index].direction === 'cw' ? '時計回り' : '反時計回り');
    assert.equal(row[3], `${encrypted.padCount}文字`);
    assert.equal(row[4].replaceAll('⏎', '\n'), GrilleLogic.formatGroups(encrypted.ciphertext));
  });
});

test('Sandorf words and reading table match the known answer', () => {
  const part = section('## 🧩 例で確かめる', '## ⌨️ キーボードショートカット');
  const code = part.match(/```text\s*([\s\S]*?)```/);
  assert.ok(code);
  const words = code[1].trim().split(/\s+/);
  assert.equal(words.length, 18);
  const sample = GrilleSamples.find(item => item.id === 'sandorf');
  const blocks = [0, 1, 2].map(column => words.filter((_word, index) => index % 3 === column).join(''));
  assert.equal(blocks.join('').toUpperCase(), sample.cipher.replace(/\s/g, ''));
  const readings = rows(part.slice(part.indexOf('| ブロック')));
  assert.equal(readings.length, 3);
  const decrypted = GrilleLogic.decrypt(sample.cipher, sample.key, { direction: sample.direction });
  readings.forEach((row, index) => {
    assert.equal(Number(row[0]), index + 1);
    assert.deepEqual(row.slice(1), decrypted.blocks[index].steps.map(step => step.letters));
  });
  assert.equal(GrilleLogic.reverseLetters(decrypted.plaintext), GrilleLogic.normalizeText(sample.original).letters);
});

test('YAML metadata keeps its HTML-comment block shape and fixed values', () => {
  const front = readme.match(/^<!--\s*\n---\s*\n([\s\S]*?)\n---\s*\n-->/);
  assert.ok(front);
  for (const key of ['category_ja', 'category_en', 'tags']) {
    assert.match(front[1], new RegExp(`^${key}:\\r?\\n  - `, 'm'));
  }
  const fixed = {
    id: 'day024',
    slug: 'grille-cipherlab',
    repo_url: '"https://github.com/ipusiron/grille-cipherlab"',
    demo_url: '"https://ipusiron.github.io/grille-cipherlab/"',
    hub: 'true'
  };
  for (const [key, value] of Object.entries(fixed)) {
    assert.match(front[1], new RegExp(`^${key}: ${value.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}$`, 'm'));
  }
});

test('relative images exist and assets contains no unreferenced PNG', () => {
  const images = [...readme.matchAll(/!\[[^\]]*\]\(([^)]+)\)/g)]
    .map(match => match[1])
    .filter(target => !/^[a-z]+:/i.test(target));
  assert.equal(images.length, 4);
  for (const image of images) assert.ok(fs.existsSync(path.join(root, image)), image);
  const referenced = images.filter(image => /^assets\/[^/]+\.png$/i.test(image)).sort();
  const actual = fs.readdirSync(path.join(root, 'assets')).filter(name => name.endsWith('.png'))
    .map(name => `assets/${name}`).sort();
  assert.deepEqual(actual, referenced);
});

function actualNodes(directory = root, relative = '') {
  const nodes = [];
  const phase2FilesDocumentedAtStage5 = new Set([
    'js/grille-solver-logic.js',
    'js/ngram-models.js',
    'js/share.js',
    'test/ngram.test.js',
    'test/share.test.js',
    'test/solver.test.js'
  ]);
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (['.git', '.claude', 'node_modules'].includes(entry.name)) continue;
    const child = relative ? `${relative}/${entry.name}` : entry.name;
    if (phase2FilesDocumentedAtStage5.has(child)) continue;
    nodes.push(child);
    if (entry.isDirectory()) nodes.push(...actualNodes(path.join(directory, entry.name), child));
  }
  return nodes.sort();
}

function treeNodes() {
  const block = section('## 📁 ディレクトリー構造', '## 💻 動作環境').match(/```text\s*([\s\S]*?)```/);
  assert.ok(block);
  const lines = block[1].trimEnd().split(/\r?\n/);
  assert.equal(lines[0].trim().split(/\s+# /)[0], 'grille-cipherlab/');
  const stack = [];
  const found = [];
  for (const line of lines.slice(1)) {
    assert.match(line, /\s+# \S/);
    const content = line.split(/\s+# /)[0];
    const marker = content.search(/[├└]── /);
    assert.notEqual(marker, -1, line);
    const depth = marker / 4 + 1;
    const name = content.slice(marker + 4).trim().replace(/\/$/, '');
    stack[depth - 1] = name;
    stack.length = depth;
    found.push(stack.join('/'));
  }
  return found.sort();
}

test('documented tree covers every repository file and directory', () => {
  assert.deepEqual(treeNodes(), actualNodes());
});

test('retired or inaccurate terminology is absent', () => {
  assert.doesNotMatch(readme, /グリフ|復号化|ルネサンス期|通常9個|CONFIG\.GRILLE_SIZE|npx serve|artnee/i);
});
